[package]
name = "apb-desktop"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "unstable"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "=1.10.0", features = ["v4", "serde"] }
time = { workspace = true }
chrono = { workspace = true }
ureq = { workspace = true }
minisign-verify = "0.2"

apb-storage = { path = "../../../crates/storage" }
apb-profiles = { path = "../../../crates/profiles" }
apb-bookmarks = { path = "../../../crates/bookmarks" }
apb-history = { path = "../../../crates/history" }
apb-tabs = { path = "../../../crates/tabs" }
apb-commands = { path = "../../../crates/commands" }
apb-notes = { path = "../../../crates/notes" }
apb-privacy = { path = "../../../crates/privacy" }
apb-network = { path = "../../../crates/network" }
apb-vault = { path = "../../../crates/vault" }
apb-ai = { path = "../../../crates/ai" }
apb-extensions = { path = "../../../crates/extensions" }

[[bin]]
name = "apb-desktop"
path = "src/main.rs"
