[package]
name = "apb-privacy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
apb-profiles = { path = "../profiles" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
